name: Build and Publish
on:
  push:
    branches:
      - main
  
  # Allow running the workflow manually
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install rust
          uses: ATiltedTree/setup-rust@v1.0.5
          with:
            rust-version: stable
        
        - name: Setup rust dev environment
          run:
            cargo install trunk &&
            rustup target add wasm32-unknown-unknown
        
        - name: Build the game
          run: trunk build --release

        - name: Setup Pages
          uses: actions/configure-pages@v3

        - name: Upload artifact
          uses: actions/upload-pages-artifact@v2
          with:
            # Upload the distribution directory
            path: './dist'

        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v2
